{{- if and (or (eq .Values.serviceMonitor "enabled") (eq (include "hasServiceMonitor" .) "enabled")) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")  }}
{{- $mtlsConfig := dict "caFile" "/etc/istio-certs/root-cert.pem" "certFile" "/etc/istio-certs/cert-chain.pem" "keyFile" "/etc/istio-certs/key.pem" "insecureSkipVerify" true -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      fullname: {{ template "base.fullname" . }}
      release: {{ .Release.Name }}
  endpoints:
  {{- if .Values.servicePorts }}
    {{- range $port_name, $port_values := .Values.servicePorts }}
    {{- if eq (default "disabled" $port_values.serviceMonitor) "enabled" }}
    - port: {{ $port_name }}
      {{- if $.Values.serviceMonitorMtls }}
      scheme: https
      tlsConfig:
        {{- $mtlsConfig | toYaml  | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- else }}
    - port: http
      {{- if $.Values.serviceMonitorMtls }}
      scheme: https
      tlsConfig:
        {{- $mtlsConfig | toYaml | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
